services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; export FLASK_APP=api/ && flask db init && flask db migrate -m "Initial migration." && flask db upgrade'
    volumes:
      - .:/app
    depends_on:
      - db

  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python runserver.py'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 5000:5000

    depends_on:
      - db
      - migration

volumes:
  pgdata:
