services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=realiz3d
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=carshop_flask
    ports:
      - 5433:5432

  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python runserver.py'
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  pgdata:
