services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=realiz3d
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=carshop_flask
    ports:
      - 5432:5432

  web:
    build: .
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  pgdata:
